// Pleasur.AI article COVER / HERO engine — Ahrefs-style flat-vector illustration (2026-06-28).
// The operator-chosen cover style: a playful, characterful FLAT-VECTOR scene illustration in the
// Ahrefs blog house-style, on a bold brand-blue (or white) background, depicting the article topic
// with objects/scenes (NO fixed mascot). NO text on the image (the page H1 carries the title); the
// real Pleasur.ai logo is composited deterministically afterward (composite_logo.py). Must pass the
// hard SFW + no-slop vision gate (VISUAL-CRITIQUE-LOOP.md → "Cover").
//
// Generated by AI (Nano Banana / Replicate) — operator override of the deterministic default for
// covers, because this characterful illustration look beats a designed card. The deterministic
// line-art engine (render_cover.py) stays as the free fallback.
//
// Usage: node cover_hero_engine.js --content c.json --out raw.png   (REPLICATE_API_KEY required)
//   c.json: { "title", "scene"?, "bg"? ("blue"|"white") }
//   `scene` is the creative variable (write it richly) — if absent it's derived from the title.
const fs = require('fs');
function arg(n, d) { const i = process.argv.indexOf('--' + n); return i > -1 ? process.argv[i + 1] : d; }
const key = process.env.REPLICATE_API_KEY;
if (!key) { console.log('FATAL: REPLICATE_API_KEY not set (mandatory — no fallback).'); process.exit(1); }
const out = arg('out', 'cover_raw.png');
const contentPath = arg('content', null);
const c = contentPath ? JSON.parse(fs.readFileSync(contentPath, 'utf8')) : { title: arg('title', 'Best AI Girlfriend Apps') };
const bg = arg('bg', c.bg || 'blue');

// SFW topic scenes — objects/scenes, no fixed mascot. The creative variable; override via c.scene.
function deriveScene(title) {
  const t = (title || '').toLowerCase();
  if (/remember|memory|forget|recall/.test(t))
    return 'a friendly smartphone with a cheerful face organising a small tidy stack of memory cards floating around it — a little photo, a heart, a coffee cup and a sticky note — with a soft thought-bubble of three simple memory icons above it';
  if (/sext|dirty|talk|flirt/.test(t))
    return 'two friendly cartoon smartphones facing each other and exchanging playful floating hearts, a small flame and chat speech-bubbles between them, with a cute slight blush on the phone screens; no people';
  if (/call|voice|phone|audio/.test(t))
    return 'a friendly smartphone with cheerful sound-wave rings radiating from it, a small heart and a tiny headset floating nearby';
  if (/safe|privacy|secure|protect|risk|scam/.test(t))
    return 'a friendly smartphone tucked safely inside a rounded shield with a small padlock and a heart, a couple of sparkles around it';
  if (/image|photo|picture|generate|art|selfie/.test(t))
    return 'a friendly smartphone with a picture frame on its screen emitting a cheerful little burst of colourful sparkles and hearts';
  if (/chat|message|conversation/.test(t))
    return 'a friendly smartphone showing a warm chat conversation full of heart and chat-bubble icons, a couple of sparkles around it';
  // default: AI girlfriend / companion apps
  return 'a simplified cheerful person sitting and smiling at a smartphone, with a warm chat conversation on the screen and friendly floating heart and chat-bubble icons around them';
}

const scene = c.scene || deriveScene(c.title);
const bgline = bg === 'white'
  ? 'BACKGROUND: a clean solid WHITE (#FFFFFF) background.'
  : 'BACKGROUND: a BOLD solid brand-blue (#2E90FA) background filling the ENTIRE frame edge to edge.';

const prompt = [
  'Create a single premium FLAT-VECTOR EDITORIAL HERO ILLUSTRATION for a modern SaaS blog, in the friendly,',
  'playful, polished house style of the Ahrefs blog.',
  'ART STYLE (match exactly): bold clean FLAT 2D VECTOR illustration; CONFIDENT, THICK, UNIFORM dark-navy',
  '(#1C2433) outlines of even weight on every shape; FLAT solid colour fills with at most one slightly',
  'darker flat tone for depth — NO gradients, NO soft airbrush shading, NO glow, NO blur; simple rounded',
  'friendly cartoon forms; clean, tidy, characterful and professional. It must look like a hand-designed',
  'vector illustration from a top product blog — NOT a 3D render, NOT photorealistic, NOT glossy, NOT clay,',
  'NOT a soft painterly AI image.',
  bgline,
  'SCENE (depict the topic literally and cheerfully): ' + scene + '.',
  'COLOUR: brand palette — primary blue #2E90FA and violet #8B5CF6 as the main colours, with mint-green',
  '#22B276 and warm coral #FF6B5C as bright accents. Cheerful and cohesive.',
  'COMPOSITION: one clear central scene with comfortable margins and generous background space around it;',
  'balanced, friendly, uncluttered; everything fully inside the frame, nothing cropped at the edges.',
  'HARD RULES: contain NO text, letters, numbers, words, captions, labels, or UI mock-text anywhere (a',
  'wordmark is added later). NO watermark, NO signature. SFW and wholesome for a public indexed blog —',
  'absolutely NO nudity, NO sexual or suggestive content, NO romantic physical contact, NO skin focus; any',
  'human characters are simple, friendly, fully-clothed cartoons with plain faces. 16:9 widescreen aspect',
  'ratio. High resolution with crisp clean vector edges.',
].join(' ');

(async () => {
  const r = await fetch('https://api.replicate.com/v1/models/google/nano-banana/predictions', {
    method: 'POST', headers: { Authorization: 'Bearer ' + key, 'Content-Type': 'application/json', 'Prefer': 'wait' },
    body: JSON.stringify({ input: { prompt, aspect_ratio: '16:9', output_format: 'png' } }), signal: AbortSignal.timeout(120000),
  });
  let pred = await r.json();
  console.log('cover-hero', bg, '| http', r.status, '| status', pred.status);
  if (pred.error) { console.log('FATAL', JSON.stringify(pred.error).slice(0, 200)); process.exit(1); }
  let n = 0;
  while (pred.urls && pred.urls.get && (pred.status === 'processing' || pred.status === 'starting') && n < 30) {
    await new Promise(s => setTimeout(s, 3000)); n++;
    pred = await (await fetch(pred.urls.get, { headers: { Authorization: 'Bearer ' + key } })).json();
  }
  const url = Array.isArray(pred.output) ? pred.output[0] : pred.output;
  if (!url) { console.log('FATAL no output', JSON.stringify(pred).slice(0, 200)); process.exit(1); }
  fs.writeFileSync(out, Buffer.from(await (await fetch(url)).arrayBuffer()));
  console.log('SAVED', out, '| scene:', scene.slice(0, 80) + '…');
})().catch(e => { console.log('FATAL', e.message); process.exit(1); });
